FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirement.txt
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]
root@worker-1:~/worker-1# cat docker-compose.yaml
version: '3.3'
services:
  worker2:
    build: /root/worker-1
    restart: always
    ports:
      - "8000:8000"